FROM openjdk:8-jre-alpine
ARG DB_USER
ARG DB_PASSWORD
ARG SPOTIFY_CLIENT_ID
ARG SPOTIFY_CLIENT_SECRET
ENV ENV_DB_USER=$DB_USER
ENV ENV_DB_PASSWORD=$DB_PASSWORD
ENV ENV_SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
ENV ENV_SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET
WORKDIR /opt/venda-discos
COPY target/venda-discos*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]