spring:
  datasource:
    url: jdbc:h2:mem:venda-discos
    #url: jdbc:h2:file:/data/venda-discos
    driverClassName: org.h2.Driver
    username: ${ENV_DB_USER}
    password: ${ENV_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
