version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn test
      - store_artifacts:
          path:  target
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
          token: 7c55e49d-cd5c-42d7-aa0c-9df9365a94a8