create table ARTISTA (
	ID bigint generated by default as identity,
	ID_SPOTIFY varchar(255) not null,
	NOME varchar(150) not null,
	primary key (ID)
);

create table ARTISTA_GENEROS (
	ARTISTA_ID bigint not null,
	GENEROS_ID bigint not null,
	primary key (ARTISTA_ID, GENEROS_ID)
);

create table CASHBACK (
	ID bigint generated by default as identity,
	DIA varchar(20) not null,
	PERCENTUAL decimal(2,2) not null,
	GENERO_ID bigint not null,
	primary key (ID)
);

create table DISCO (
	ID bigint generated by default as identity,
	ID_SPOTIFY varchar(255) not null,
	NOME varchar(150) not null,
	PRECO decimal(19,2) not null,
	primary key (ID)
);

create table DISCO_ARTISTAS (
	DISCO_ID bigint not null,
	ARTISTAS_ID bigint not null,
	primary key (DISCO_ID, ARTISTAS_ID)
);

create table GENERO (
	ID bigint generated by default as identity,
	NOME varchar(50) not null,
	primary key (id)
);

create table ITEM (
	ID bigint generated by default as identity,
	CASHBACK decimal(19,2) not null,
	QUANTIDADE integer not null,
	VALOR decimal(19,2) not null,
	DISCO_ID bigint not null,
	VENDA_ID bigint not null,
	primary key (ID)
);

create table VENDA (
	ID bigint generated by default as identity,
	DATA timestamp not null,
	primary key (ID)
);

alter table ARTISTA add constraint UK_ARTISTA_ID_SPOTIFY unique (ID_SPOTIFY);

alter table DISCO add constraint UK_DISCO_ID_SPOTIFY unique (ID_SPOTIFY);

alter table ARTISTA_GENEROS add constraint FK_ARTISTA_GENEROS_GENERO foreign key (GENEROS_ID) references GENERO;

alter table ARTISTA_GENEROS add constraint FK_ARTISTA_GENEROS_ARTISTA foreign key (ARTISTA_ID) references ARTISTA;

alter table CASHBACK add constraint FK_CASHBACK_GENERO foreign key (GENERO_ID) references GENERO;

alter table DISCO_ARTISTAS add constraint FK_DISCO_ARTISTAS_ARTISTA foreign key (ARTISTAS_ID) references ARTISTA;

alter table DISCO_ARTISTAS add constraint FK_DISCO_ARTISTAS_DISCO foreign key (DISCO_ID) references DISCO;

alter table ITEM add constraint FK_ITEM_DISCO foreign key (DISCO_ID) references DISCO;

alter table ITEM add constraint FK_ITEM_VENDA foreign key (VENDA_ID) references VENDA;
