create table CASHBACK (
	ID bigint generated by default as identity,
	DIA varchar(20) not null,
	PERCENTUAL decimal(2,2) not null,
	GENERO_ID bigint not null,
	primary key (ID)
);

create table DISCO (
	ID bigint generated by default as identity,
	ARTISTAS varchar(300),
	NOME varchar(100) not null,
	PRECO decimal(19,2) not null,
	primary key (ID)
);

create table GENERO (
	ID bigint generated by default as identity,
	NOME varchar(50) not null,
	primary key (id)
);

create table ITEM (
	ID bigint generated by default as identity,
	CASHBACK decimal(19,2) not null,
	QUANTIDADE integer not null,
	VALOR decimal(19,2) not null,
	DISCO_ID bigint not null,
	VENDA_ID bigint not null,
	primary key (ID)
);

create table VENDA (
	ID bigint generated by default as identity,
	DATA timestamp not null,
	primary key (ID)
);

alter table CASHBACK add constraint FK_CASHBACK_GENERO foreign key (GENERO_ID) references GENERO;

alter table ITEM add constraint FK_ITEM_DISCO foreign key (DISCO_ID) references DISCO;

alter table ITEM add constraint FK_ITEM_VENDA foreign key (VENDA_ID) references VENDA;
