INSERT INTO GENERO 
	(NOME)
VALUES
	('POP'),
	('MPB'),
	('CLASSIC'),
	('ROCK');

INSERT INTO CASHBACK
	(DIA, PERCENTUAL, GENERO_ID)
VALUES
	(0, 0.25, (SELECT ID GENERO FROM GENERO WHERE NOME = 'POP')),
	(1, 0.07, (SELECT ID GENERO FROM GENERO WHERE NOME = 'POP')),
	(2, 0.06, (SELECT ID GENERO FROM GENERO WHERE NOME = 'POP')),
	(3, 0.02, (SELECT ID GENERO FROM GENERO WHERE NOME = 'POP')),
	(4, 0.10, (SELECT ID GENERO FROM GENERO WHERE NOME = 'POP')),
	(5, 0.15, (SELECT ID GENERO FROM GENERO WHERE NOME = 'POP')),
	(6, 0.20, (SELECT ID GENERO FROM GENERO WHERE NOME = 'POP')),
	
	(0, 0.30, (SELECT ID GENERO FROM GENERO WHERE NOME = 'MPB')),
	(1, 0.05, (SELECT ID GENERO FROM GENERO WHERE NOME = 'MPB')),
	(2, 0.10, (SELECT ID GENERO FROM GENERO WHERE NOME = 'MPB')),
	(3, 0.15, (SELECT ID GENERO FROM GENERO WHERE NOME = 'MPB')),
	(4, 0.20, (SELECT ID GENERO FROM GENERO WHERE NOME = 'MPB')),
	(5, 0.25, (SELECT ID GENERO FROM GENERO WHERE NOME = 'MPB')),
	(6, 0.30, (SELECT ID GENERO FROM GENERO WHERE NOME = 'MPB')),
	
	(0, 0.35, (SELECT ID GENERO FROM GENERO WHERE NOME = 'CLASSIC')),
	(1, 0.03, (SELECT ID GENERO FROM GENERO WHERE NOME = 'CLASSIC')),
	(2, 0.05, (SELECT ID GENERO FROM GENERO WHERE NOME = 'CLASSIC')),
	(3, 0.08, (SELECT ID GENERO FROM GENERO WHERE NOME = 'CLASSIC')),
	(4, 0.13, (SELECT ID GENERO FROM GENERO WHERE NOME = 'CLASSIC')),
	(5, 0.18, (SELECT ID GENERO FROM GENERO WHERE NOME = 'CLASSIC')),
	(6, 0.25, (SELECT ID GENERO FROM GENERO WHERE NOME = 'CLASSIC')),
	
	(0, 0.40, (SELECT ID GENERO FROM GENERO WHERE NOME = 'ROCK')),
	(1, 0.10, (SELECT ID GENERO FROM GENERO WHERE NOME = 'ROCK')),
	(2, 0.15, (SELECT ID GENERO FROM GENERO WHERE NOME = 'ROCK')),
	(3, 0.15, (SELECT ID GENERO FROM GENERO WHERE NOME = 'ROCK')),
	(4, 0.15, (SELECT ID GENERO FROM GENERO WHERE NOME = 'ROCK')),
	(5, 0.20, (SELECT ID GENERO FROM GENERO WHERE NOME = 'ROCK')),
	(6, 0.40, (SELECT ID GENERO FROM GENERO WHERE NOME = 'ROCK'));
